Repository boostcampwm-2021/web31-MAFIA31, pull requests merged in 2021-11, with the labels that each got.

#7 [TASK] 소켓 설정
  .github/ISSUE_TEMPLATE/considering-report-template.md
  .github/ISSUE_TEMPLATE/task-report-template.md
  packages/client/package.json
  packages/client/src/hooks/useChat.ts
  packages/server/.eslintrc.json
  packages/server/index.ts
  packages/server/loaders/express.ts
  packages/server/loaders/index.ts
  packages/server/loaders/socket.ts
  packages/server/loaders/sockets/chat.ts
  packages/server/loaders/sockets/index.ts
  packages/server/package.json
  yarn.lock
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#6 [TASK] 채팅을 입력하고 전송할 UI 구현
  packages/client/package.json
  packages/client/public/assets/icons/enter.png
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/constants/colors.ts
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/types/ChatTypes.ts
  packages/client/tsconfig.json
  yarn.lock
Labels: 🧩 Component, 👶🏻 Frontend

#23 Feat/game over
  packages/domain/types/game.ts
  packages/server/loaders/sockets/game.ts
  packages/server/loaders/sockets/index.ts
Labels: ✨ Feature, 💻 Backend

#25 [TASK] 사용자 투표 기능 구현
  packages/client/public/assets/icons/vote.png
  packages/client/src/components/Card/VoteCard.tsx
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/constants/colors.ts
  packages/client/src/constants/index.ts
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/GameLeftSideContainer.tsx
  packages/client/src/pages/Game/index.tsx
  packages/domain/types/user.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#26 [TASK] 투표 컴포넌트 UI 생성 및 투표 소켓 커스텀 훅 구현
  packages/client/src/components/Button/AbilityBtn.tsx
  packages/client/src/containers/VoteContainer.tsx
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/types/vote.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#31 [REFACTOR] 게임 페이지 스타일 리팩토링
  packages/client/public/assets/icons/enter.png
  packages/client/public/assets/icons/send(dark).png
  packages/client/public/assets/icons/send(light).png
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/index.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/styles/reset.min.css
Labels: 🧩 Component, ⚙️ Refactor, 👶🏻 Frontend

#29 [TASK] 로그인 페이지 구현
  packages/client/public/assets/icons/github.png
  packages/client/public/assets/icons/home.png
  packages/client/src/App.tsx
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Login/index.tsx
  packages/server/loaders/sockets/game.ts
Labels: 🧩 Component, 👶🏻 Frontend, 💻 Backend

#57 [REFACTOR] 소켓 리팩토링
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/components/Card/RoomCard.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useExecute.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/pages/Rooms/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/chat.ts
  packages/server/loaders/socket.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/game.ts
  packages/server/sockets/index.ts
  packages/server/sockets/vote.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#58 [Task] Github OAuth 로그인 구현
  packages/client/.eslintrc.json
  packages/client/src/App.tsx
  packages/client/src/contexts/userInfo.tsx
  packages/client/src/pages/Callback/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/server/api/auth/auth.controller.ts
  packages/server/api/auth/index.ts
  packages/server/loaders/express.ts
  packages/server/loaders/index.ts
  packages/server/loaders/router.ts
  packages/server/package.json
  yarn.lock
Labels: 🕊 API, 👶🏻 Frontend, 💻 Backend

#59 [TASK] Game page UI 구현
  packages/client/.eslintrc.json
  packages/client/public/assets/icons/profile.svg
  packages/client/public/assets/icons/send.svg
  packages/client/public/assets/icons/vote.png
  packages/client/public/assets/icons/vote.svg
  packages/client/public/assets/images/citizen.png
  packages/client/public/assets/images/home.png
  packages/client/public/assets/images/mafia.png
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Card/ResultCard.tsx
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/index.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/styles/reset.css
  packages/client/src/types/index.ts
  packages/client/tsconfig.paths.json
  packages/domain/types/vote.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
Labels: 🧩 Component, 📄 Page, 👶🏻 Frontend

#61 [TASK] Game 페이지 UI 구현
  packages/client/public/assets/icons/exit.png
  packages/client/public/assets/icons/profile.png
  packages/client/public/assets/icons/profile.svg
  packages/client/public/assets/icons/send(dark).png
  packages/client/public/assets/icons/send(light).png
  packages/client/public/assets/icons/send.svg
  packages/client/public/assets/images/citizen.png
  packages/client/public/assets/images/doctor.png
  packages/client/public/assets/images/mafia.png
  packages/client/public/assets/images/moon.png
  packages/client/public/assets/images/police.png
  packages/client/public/assets/images/sun.png
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Button/Button.st.tsx
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/components/Button/IconButton.tsx
  packages/client/src/components/Button/MemoButton.tsx
  packages/client/src/components/Button/index.ts
  packages/client/src/components/Icon/index.tsx
  packages/client/src/components/Icon/room-out.svg
  packages/client/src/components/Icon/search.svg
  packages/client/src/components/Icon/send.svg
  packages/client/src/components/Icon/setting.svg
  packages/client/src/components/Icon/vote.svg
  packages/client/src/components/Image/index.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useExecute.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Waiting/index.tsx
Labels: 📄 Page, ⚙️ Refactor, 👶🏻 Frontend

#63 [TASK] 대기방 페이지 UI
  packages/client/public/assets/icons/host.png
  packages/client/src/components/Card/ProfileCard.tsx
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/templates/Header/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/user.ts
Labels: 🧩 Component, 📄 Page, 👶🏻 Frontend

#65 [TASK] 업적 페이지 UI 구현
  packages/client/.eslintrc.json
  packages/client/public/assets/images/trophy.png
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/components/Button/index.ts
  packages/client/src/components/Card/AchievementCard.tsx
  packages/client/src/components/Image/index.tsx
  packages/client/src/constants/colors.ts
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/pages/Profile/dummyData.ts
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/templates/Header/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/achievement.ts
  packages/domain/types/user.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/index.ts
Labels: 🧩 Component, 📄 Page, 👶🏻 Frontend

#62 [TASK] 랜덤 직업 할당 구현
  packages/server/constants/job.ts
  packages/server/sockets/game.ts
Labels: ✨ Feature, 💻 Backend

#64 [TASK] 사용자 준비 및 방장 시작 구현
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/hooks/useRoom.ts
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/templates/Header/index.tsx
  packages/domain/constants/event.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#68 [TASK] 방마다 입장 user 정보를 저장
  packages/client/src/hooks/useRoom.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/pages/Waiting/index.tsx
  packages/domain/types/user.ts
  packages/server/sockets/index.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#73 [TASK] 밤 채팅 구현
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useTimer.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/constants/event.ts
  packages/domain/types/chat.ts
  packages/server/sockets/chat.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#70 [TASK] 대기방 페이지 데이터 서버와 연동 #47
  packages/client/src/hooks/useRoom.ts
  packages/client/src/pages/Waiting/index.tsx
  packages/server/sockets/dummy.ts
  packages/server/sockets/game.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#69 [TASK] 직업 할당 구현
  packages/client/.eslintrc.json
  packages/client/src/constants/index.ts
  packages/client/src/constants/job.ts
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useGame.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/constants/event.ts
  packages/server/constants/job.ts
  packages/server/sockets/game.ts
  packages/server/sockets/index.ts
  packages/server/stores/RoomStore.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#74 [TASK] 타이머 디스플레이 구현
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useTimer.ts
  packages/client/src/pages/Game/index.tsx
Labels: ✨ Feature, 👶🏻 Frontend

#72 [TASK] 마피아 능력 사용 + 밤낮 테마 바꾸기
  packages/client/public/assets/icons/exit.svg
  packages/client/public/assets/icons/undo.svg
  packages/client/public/assets/images/skull.png
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/components/Button/IconButton.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/domain/constants/event.ts
  packages/domain/types/game.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/game.ts
  packages/server/sockets/index.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#76 [Refactor] 서버 리팩토링
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/hooks/useExecute.ts
  packages/client/src/hooks/useRoom.ts
  packages/client/src/pages/Waiting/index.tsx
  packages/domain/types/game.ts
  packages/domain/types/user.ts
  packages/server/constants/job.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/dummy.ts
  packages/server/sockets/game.ts
  packages/server/sockets/index.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
  packages/server/stores/RoomStore.ts
Labels: ⚙️ Refactor

#77 [Refactor] Client UI 리팩토링
  packages/client/.eslintrc.json
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/components/Card/AchievementCard.tsx
  packages/client/src/components/Card/ProfileCard.tsx
  packages/client/src/components/Card/RoomCard.tsx
  packages/client/src/components/Image/index.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/hooks/useTimer.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Rooms/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/templates/Header/index.tsx
  packages/client/src/utils/time-displayer.ts
  packages/client/tsconfig.paths.json
Labels: ⚙️ Refactor

#79 [REFACTOR] config 파일 설정
  .gitignore
  packages/server/api/auth/auth.controller.ts
  packages/server/api/room/room.controller.ts
  packages/server/loaders/db.ts
  packages/server/loaders/express.ts
  packages/server/package.json
  yarn.lock
Labels: 🏝 Environment, ⚙️ Refactor

#87 [TASK] 투표 결과 스토리 메세지로 연결
  packages/client/public/assets/images/die-vote.png
  packages/client/src/components/Image/index.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/hooks/useChat.ts
  packages/client/src/types/index.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#86 [TASK] 스토리 카드 구현 및 마피아 능력 연결
  packages/client/public/assets/images/doctor-heal.PNG
  packages/client/public/assets/images/mafia-kill.PNG
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/constants/story.ts
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useExecute.ts
  packages/client/src/hooks/useGame.ts
  packages/client/src/hooks/useRoom.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/hooks/useTimer.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/types/index.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend, 💻 Backend

#81 [TASK] 게임 종료 후 결과 페이지로 반영
  packages/client/src/components/Card/ResultCard.tsx
  packages/client/src/hooks/useGame.ts
  packages/client/src/hooks/useRoom.ts
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/domain/constants/event.ts
  packages/domain/types/game.ts
  packages/server/sockets/game.ts
  packages/server/sockets/index.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, 📄 Page, ⚙️ Refactor, 👶🏻 Frontend

#82 [TASK] socket을 context로 관리
  packages/client/src/App.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/contexts/socket.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useExecute.ts
  packages/client/src/hooks/useGame.ts
  packages/client/src/hooks/useRoom.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/hooks/useTimer.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Callback/index.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/utils/disconnectSocket.ts
Labels: ✨ Feature, ⚙️ Refactor, 👶🏻 Frontend

#88 [TASK] 프로필 이미지 추가 및 커스텀훅 리팩토링
  packages/client/public/assets/images/question.png
  packages/client/src/components/Button/DefaultButton.tsx
  packages/client/src/components/Card/ProfileCard.tsx
  packages/client/src/components/Image/index.tsx
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/constants/colors.ts
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useRoom.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/domain/types/game.ts
  packages/domain/types/user.ts
  packages/domain/types/vote.ts
  packages/server/api/auth/auth.controller.ts
  packages/server/sockets/game.ts
  packages/server/sockets/index.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
  packages/server/stores/RoomStore.ts
Labels: ✨ Feature, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#103 [TASK] 토스트 메시지 구현 & 커스텀 훅 추가 & 헤더로고 변경
  packages/client/package.json
  packages/client/public/assets/icons/dark-logo.svg
  packages/client/src/components/Icon/index.tsx
  packages/client/src/components/Icon/light-logo.svg
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/hooks/usePreventLeave.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/templates/Header/index.tsx
  yarn.lock
Labels: ✨ Feature, 👶🏻 Frontend

#104 [TASK] 기초 통계 데이터 DB에 저장 및 업데이트 구현
  packages/server/api/auth/auth.controller.ts
  packages/server/api/room/room.controller.ts
  packages/server/api/user/index.ts
  packages/server/api/user/user.controller.ts
  packages/server/api/user/user.service.ts
  packages/server/loaders/express.ts
  packages/server/loaders/router.ts
  packages/server/models/Room.ts
  packages/server/models/User.ts
  packages/server/sockets/game.ts
Labels: ✨ Feature, 🕊 API, ⚙️ Refactor, 💻 Backend

#107 [TASK] 투표 버그 픽스
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/types/game.ts
  packages/domain/types/vote.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: 🐞 Bug, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#108 [TASK] 게임페이지 직업 설명 모달 구현
  packages/client/public/assets/images/user.png
  packages/client/src/components/Card/RoleCard.tsx
  packages/client/src/components/Icon/index.tsx
  packages/client/src/components/Icon/slide-left.svg
  packages/client/src/components/Icon/slide-right.svg
  packages/client/src/components/Modal/index.tsx
  packages/client/src/constants/job.ts
  packages/client/src/containers/RightSideContainer.tsx
Labels: 🧩 Component, 👶🏻 Frontend

#106 [TASK] 커스텀 훅 서버 데이터와 연결
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useRoom.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/game.ts
  packages/domain/types/vote.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, ⚙️ Refactor, 👶🏻 Frontend

#110 [FIX] syntax error 해결
  packages/client/src/containers/RightSideContainer.tsx
Labels: 🐞 Bug, 👶🏻 Frontend

#114 [TASK] 사망시 투표 및 채팅 비활성화
  packages/client/.eslintrc.json
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/tsconfig.paths.json
  packages/server/sockets/ability.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, 🐞 Bug, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#115 [FIX] 투표 한번만 하도록 설정
  packages/server/stores/GameStore.ts
Labels: 🐞 Bug, 💻 Backend

#116 [FIX] 첫번째 낮 밤 변경 버그 수정
  packages/client/src/constants/toast.ts
  packages/client/src/hooks/useTimer.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/constants/event.ts
  packages/domain/constants/time.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
Labels: 🐞 Bug, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#117 [TASK] 경찰 직업 추가
  packages/client/src/components/Card/ResultCard.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/domain/constants/event.ts
  packages/domain/types/game.ts
  packages/server/constants/job.ts
  packages/server/models/User.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/game.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, 🐞 Bug, 👶🏻 Frontend, 💻 Backend

#118 [TASK] 마피아 능력 수정
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/constants/story.ts
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useExecute.ts
  packages/client/src/hooks/usePlayerState.ts
  packages/client/src/pages/Game/index.tsx
  packages/server/sockets/ability.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: 🐞 Bug

#123 [REFACTOR} 투표 및 토스트 메세지 리팩토링
  packages/client/src/pages/Game/index.tsx
  packages/domain/constants/time.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#124 [TASK] MP4 애니메이션 구현
  README.md
  packages/client/.eslintrc.json
  packages/client/public/assets/images/mafia-kill.mp4
  packages/client/public/assets/images/vote-kill.png
  packages/client/src/components/Image/index.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/constants/story.ts
  packages/client/src/hooks/useChat.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#125 [TASK] 의사,경찰 능력 구현
  packages/client/src/components/Card/ResultCard.tsx
  packages/client/src/constants/story.ts
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useGame.ts
  packages/client/src/types/index.ts
  packages/domain/constants/event.ts
  packages/domain/types/chat.ts
  packages/domain/types/game.ts
  packages/server/constants/job.ts
  packages/server/models/User.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#126 [TASK] 게임 종료 후 방 나가기 기능
  packages/client/src/pages/GameResult/index.tsx
Labels: ✨ Feature, 👶🏻 Frontend

#127 [TASK] 유저 정보 조회 API 구현
  packages/client/src/containers/RoomContainer.tsx
  packages/server/api/user/index.ts
  packages/server/api/user/user.controller.ts
  packages/server/api/user/user.service.ts
  packages/server/loaders/router.ts
  packages/server/sockets/game.ts
Labels: 🕊 API, ⚙️ Refactor, 💻 Backend

#128 [REFACTOR] 프론트엔드 리팩토링
  packages/client/public/assets/icons/back.svg
  packages/client/public/assets/icons/black-logo.svg
  packages/client/public/assets/icons/exit.svg
  packages/client/public/assets/icons/logout.svg
  packages/client/public/assets/icons/person.svg
  packages/client/public/assets/icons/undo.png
  packages/client/public/assets/icons/undo.svg
  packages/client/public/assets/images/question.png
  packages/client/public/favicon.ico
  packages/client/public/index.html
  packages/client/src/components/Card/AchievementCard.tsx
  packages/client/src/components/Card/ResultCard.tsx
  packages/client/src/components/Card/RoomCard.tsx
  packages/client/src/components/Icon/index.tsx
  packages/client/src/components/Icon/logo-light.svg
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/components/Modal/index.tsx
  packages/client/src/constants/colors.ts
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Rooms/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/templates/Header/index.tsx
Labels: ⚙️ Refactor, 👶🏻 Frontend

#133 [FIX] 플레이어 죽음 반영 버그
  packages/client/public/assets/icons/dark-logo.svg
  packages/client/public/assets/icons/profile.png
  packages/client/public/assets/images/mafia.png
  packages/client/src/hooks/usePlayerState.ts
  packages/client/src/pages/GameResult/index.tsx
Labels: 🐞 Bug, 👶🏻 Frontend

#139 [TASK] 밤 시간 30초로 변경
  packages/domain/constants/time.ts
  packages/server/sockets/game.ts
Labels: ✨ Feature, 💻 Backend

#144 [TASK] 의사 능력 사용 애니메이션 추가
  packages/client/public/assets/images/healthcare.png
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/pages/Game/index.tsx
Labels: ✨ Feature, 👶🏻 Frontend

#148 [TASK] Express 에러 핸들링
  .gitignore
  packages/server/api/room/room.controller.ts
  packages/server/error/ApplicationError.ts
  packages/server/error/InternalServerError.ts
  packages/server/error/InvalidRoomIdError.ts
  packages/server/error/errorHandler.ts
  packages/server/loaders/errorHandlerLoader.ts
  packages/server/loaders/index.ts
Labels: ✨ Feature, 💻 Backend

#149 [TASK] 직업 배정시 마피아끼리 알려주기
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Button/MemoButton.tsx
  packages/client/src/constants/story.ts
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/usePlayerState.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/types/index.ts
  packages/domain/constants/event.ts
  packages/domain/types/chat.ts
  packages/domain/types/game.ts
  packages/server/sockets/game.ts
Labels: 👶🏻 Frontend

#150 [TASK] 이미 시작한 방에 들어가지 못하게 하기
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/server/api/room/index.ts
  packages/server/api/room/room.controller.ts
  packages/server/models/Room.ts
  packages/server/sockets/game.ts
  yarn.lock
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#154 [TASK] 마피아 능력사용 수정
  packages/server/sockets/ability.ts
Labels: 🐞 Bug, 💻 Backend

#155 [TASK] 로그인 관련 JWT 토큰 및 쿠키 추가 구현
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/components/Route/SocketRoute.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/index.tsx
  packages/client/src/pages/Callback/index.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Login/index.tsx
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/types/index.ts
  packages/client/tsconfig.json
  packages/server/api/auth/auth.controller.ts
  packages/server/api/room/room.controller.ts
  packages/server/loaders/express.ts
  packages/server/package.json
  packages/server/sockets/game.ts
  yarn.lock
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#156 [TASK] 이미 게임을 시작한 방에 들어가려하면 모달 띄워주기
  packages/client/package.json
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/types/index.ts
  packages/server/sockets/game.ts
  yarn.lock
Labels: ✨ Feature, 👶🏻 Frontend

#160 [FIX] 방에 아무도 없을때 방 상태 업데이트
  packages/server/stores/RoomStore.ts
Labels: 🐞 Bug

#162 [TASK] 게임 페이지에서 방 나가기
  .gitignore
  packages/client/src/components/Modal/ConfirmModal.tsx
  packages/client/src/components/Modal/CustomModal.tsx
  packages/client/src/components/Modal/NoticeModal.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/hooks/useModal.ts
  packages/client/src/hooks/usePlayerState.ts
  packages/domain/constants/event.ts
  packages/server/sockets/index.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#163 [TASK] 통계 페이지에 데이터 반영 및 UI 수정
  packages/client/src/components/Card/JobStatCard.tsx
  packages/client/src/containers/JobStatContainer.tsx
  packages/client/src/pages/Profile/index.tsx
  packages/client/tsconfig.json
  packages/domain/types/game.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#168 [TASK] 죽은 사람끼리 채팅
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/pages/Game/index.tsx
  packages/server/sockets/ability.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: ✨ Feature, 🐞 Bug, 👶🏻 Frontend, 💻 Backend

#170 [TASK] API 인증 미들웨어 추가
  packages/client/src/App.tsx
  packages/client/src/axios/apiClient.ts
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/pages/Callback/index.tsx
  packages/server/api/auth/auth.controller.ts
  packages/server/api/room/room.controller.ts
  packages/server/api/room/room.service.ts
  packages/server/api/user/index.ts
  packages/server/api/user/user.controller.ts
  packages/server/api/user/user.service.ts
  packages/server/axios/apiClient.ts
  packages/server/error/BadRequsetError.ts
  packages/server/error/InvalidRoomIdError.ts
  packages/server/error/NotFoundError.ts
  packages/server/error/UnauthorizedError.ts
  packages/server/error/errorHandler.ts
  packages/server/loaders/errorHandlerLoader.ts
  packages/server/loaders/router.ts
  packages/server/middlewares/auth.ts
  packages/server/sockets/game.ts
Labels: 🕊 API, ⚙️ Refactor, 💻 Backend

#180 [FIX] 소켓에서의 API 요청 수정
  packages/server/axios/apiClient.ts
  packages/server/error/MethodNotAllowedError.ts
  packages/server/loaders/express.ts
  packages/server/loaders/router.ts
  packages/server/loaders/socket.ts
  packages/server/package.json
  packages/server/sockets/index.ts
  packages/server/stores/RoomStore.ts
  yarn.lock
Labels: 🐞 Bug, 💻 Backend

#182 [TASK] 통계페이지 탭 및 차트 추가
  packages/client/package.json
  packages/client/src/components/Card/JobStatCard.tsx
  packages/client/src/components/Chart/PieChart.tsx
  packages/client/src/containers/AchievementListContainer.tsx
  packages/client/src/hooks/useTab.ts
  packages/client/src/pages/Profile/index.tsx
  yarn.lock
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#184 [TASK] 마피아 밤 채팅 & 죽은 사람 채팅 오류 해결
  packages/client/src/components/Message/ChatMsg.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/constants/colors.ts
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/hooks/useChat.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/types/chat.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/game.ts
  packages/server/stores/GameStore.ts
  packages/server/stores/RoomStore.ts
Labels: ✨ Feature, 🐞 Bug, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend

#185 [TASK] 방 생성 기능 추가
  packages/client/src/components/Card/RoomCard.tsx
  packages/client/src/containers/RoomContainer.tsx
  packages/client/src/containers/RoomFormContainer.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/templates/Header/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/room.ts
  packages/server/api/room/index.ts
  packages/server/api/room/room.controller.ts
  packages/server/api/room/room.service.ts
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend, 💻 Backend

#186 [TASK] 음소거 버튼 추가 및 찬반 투표 추가
  packages/client/src/components/Button/IconButton.tsx
  packages/client/src/components/Icon/Vector.svg
  packages/client/src/components/Icon/index.tsx
  packages/client/src/components/Icon/mute.svg
  packages/client/src/components/Icon/volume.svg
  packages/client/src/components/Modal/CrossVoteModal.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useAudio.ts
  packages/client/src/hooks/useVoteModal.ts
  packages/client/src/pages/Game/index.tsx
  packages/domain/constants/event.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
Labels: ✨ Feature

#187 [TASK] 메모 기능 구현
  packages/client/public/assets/images/loading.gif
  packages/client/src/components/Button/MemoButton.tsx
  packages/client/src/components/Modal/ConfirmModal.tsx
  packages/client/src/components/Modal/CustomModal.tsx
  packages/client/src/components/Modal/MemoModal.tsx
  packages/client/src/components/Modal/NoticeModal.tsx
  packages/client/src/constants/index.ts
  packages/client/src/constants/job.ts
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/usePlayerState.ts
  packages/client/src/pages/Game/index.tsx
Labels: ✨ Feature, 🧩 Component, 👶🏻 Frontend

#189 [TASK] 영매 직업 추가
  packages/client/public/assets/images/shaman.png
  packages/server/constants/job.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/chat.ts
  packages/server/sockets/vote.ts
Labels: ✨ Feature, 💻 Backend

#196 [TASK] 스토리 카드 애니메이션 추가 및 리팩토링
  packages/client/public/assets/images/mafias.mp4
  packages/client/public/assets/images/peaceful-day.mp4
  packages/client/public/assets/images/police-catch.mp4
  packages/client/public/assets/images/police-wrong.mp4
  packages/client/src/animation/ExecuteAnimation.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/components/Modal/CrossVoteModal.tsx
  packages/client/src/components/Modal/CustomModal.tsx
  packages/client/src/constants/story.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/chat.ts
  packages/domain/types/game.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/vote.ts
Labels: ✨ Feature, 🧩 Component, 🐞 Bug, ⚙️ Refactor, 👶🏻 Frontend

#197 [TASK] 스토리 카드 애니메이션 추가 및 리팩토링 (#196)
  packages/client/public/assets/images/mafias.mp4
  packages/client/public/assets/images/peaceful-day.mp4
  packages/client/public/assets/images/police-catch.mp4
  packages/client/public/assets/images/police-wrong.mp4
  packages/client/src/animation/ExecuteAnimation.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/components/Modal/CrossVoteModal.tsx
  packages/client/src/components/Modal/CustomModal.tsx
  packages/client/src/constants/story.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/types/index.ts
  packages/domain/types/chat.ts
  packages/domain/types/game.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/vote.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend

#199 [REFACTOR] 커스텀 훅 리팩토링
  packages/client/public/assets/audios/bullet.mp3
  packages/client/public/assets/audios/check.mp3
  packages/client/public/assets/audios/clank.mp3
  packages/client/public/assets/audios/effect1.mp3
  packages/client/public/assets/audios/heal.mp3
  packages/client/public/assets/images/check.png
  packages/client/public/assets/images/heal.png
  packages/client/public/assets/images/search.png
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/components/Message/StoryMsg.tsx
  packages/client/src/constants/audio.ts
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useAudioo.ts
  packages/client/src/hooks/useChat.ts
  packages/client/src/hooks/useGame.ts
  packages/client/src/hooks/useLog.ts
  packages/client/src/hooks/useMemo.ts
  packages/client/src/hooks/usePlayerState.ts
  packages/client/src/hooks/useRoom.ts
  packages/client/src/hooks/useSocket.ts
  packages/client/src/hooks/useSocketEvent.ts
  packages/client/src/hooks/useTimer.ts
  packages/client/src/hooks/useVote.ts
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/types/index.ts
  packages/domain/constants/event.ts
  packages/domain/types/chat.ts
  packages/domain/types/vote.ts
  packages/server/constants/story.ts
  packages/server/sockets/ability.ts
  packages/server/sockets/game.ts
  packages/server/sockets/vote.ts
  packages/server/stores/GameStore.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend

#200 [TASK] 부하 테스트 기본 설정
  .gitignore
  .vscode/settings.json
  packages/server/artillery/hooks/index.js
  packages/server/artillery/test.yml
  packages/server/package.json
  yarn.lock
Labels: 🏝 Environment, 💻 Backend

#202 [FIX] 경찰 능력 사용
  packages/client/src/hooks/useAbility.ts
  packages/domain/constants/event.ts
  packages/server/sockets/ability.ts
Labels: 🐞 Bug

#204 [REFACTOR] 컴포넌트 분리 작업
  packages/client/src/containers/ChatContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/ProfileLeftSideContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/containers/TabContainer.tsx
  packages/client/src/lists/AbilityButtonList.tsx
  packages/client/src/lists/AchievementListContainer.tsx
  packages/client/src/lists/ChatMsgList.tsx
  packages/client/src/lists/JobStatContainer.tsx
  packages/client/src/lists/MemoList.tsx
  packages/client/src/lists/ResultCardList.tsx
  packages/client/src/lists/RoomContainer.tsx
  packages/client/src/lists/WaitingListContainer.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Rooms/index.tsx
  packages/client/src/pages/Waiting/index.tsx
Labels: 🧩 Component, ⚙️ Refactor, 👶🏻 Frontend

#205 [REFACTOR] 커스텀 훅 리팩토링
  packages/client/src/components/Modal/ConfirmModal.tsx
  packages/client/src/components/Modal/CrossVoteModal.tsx
  packages/client/src/constants/toast.ts
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useAudio.ts
  packages/client/src/hooks/useAudioo.ts
  packages/client/src/hooks/useExecutionModal.ts
  packages/client/src/hooks/useToast.ts
  packages/client/src/hooks/useVoteModal.ts
  packages/client/src/lists/AbilityButtonList.tsx
  packages/client/src/lists/JobStatContainer.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/GameResult/index.tsx
  packages/domain/types/game.ts
  packages/domain/types/vote.ts
  packages/server/constants/job.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend

#206 [TASK] 소켓 서버 패키지로 분리
  package.json
  packages/client/tsconfig.json
  packages/server/loaders/index.ts
  packages/server/package.json
  packages/socket/.eslintrc.json
  packages/socket/artillery/hooks/index.js
  packages/socket/artillery/test.yml
  packages/socket/axios/apiClient.ts
  packages/socket/constants/job.ts
  packages/socket/constants/story.ts
  packages/socket/index.ts
  packages/socket/package.json
  packages/socket/sockets/ability.ts
  packages/socket/sockets/chat.ts
  packages/socket/sockets/game.ts
  packages/socket/sockets/index.ts
  packages/socket/sockets/vote.ts
  packages/socket/stores/GameStore.ts
  packages/socket/stores/RoomStore.ts
  packages/socket/tsconfig.json
Labels: 🏝 Environment

#208 [FIX] 플레이어 없을시 타이머 초기화 및 방 나가기 적용 안됨 문제 해결
  packages/client/src/pages/Profile/index.tsx
  packages/client/src/pages/Rooms/index.tsx
  packages/client/src/templates/Header/index.tsx
  packages/socket/sockets/game.ts
  packages/socket/sockets/index.ts
  packages/socket/stores/GameStore.ts
  packages/socket/stores/RoomStore.ts
Labels: 🐞 Bug, ⚙️ Refactor, 👶🏻 Frontend, 💻 Backend
