Repository boostcampwm-2021/web31-MAFIA31, pull requests merged in 2021-12, with the labels that each got.

#210 [TASK] 로그인 만료시 처리
  packages/client/src/App.tsx
  packages/client/src/axios/InjectAxiosInterceptors.tsx.ts
  packages/client/src/axios/apiClient.ts
  packages/client/tsconfig.json
  packages/server/middlewares/auth.ts
  packages/server/package.json
Labels: 🐞 Bug

#214 [TASK] 방 정보 연동
  packages/client/public/assets/icons/link.png
  packages/client/public/assets/images/not-found.png
  packages/client/src/App.tsx
  packages/client/src/axios/apiClient.ts
  packages/client/src/components/Card/RoomCard.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hooks/useRoom.ts
  packages/client/src/lists/RoomList.tsx
  packages/client/src/pages/Callback/index.tsx
  packages/client/src/pages/Error/NotFound.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Rooms/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/server/api/room/room.controller.ts
  packages/server/api/room/room.service.ts
Labels: ✨ Feature, 👶🏻 Frontend, 💻 Backend

#216 [TASK] 점수 라인 그래프 추가
  packages/client/package.json
  packages/client/src/components/Card/JobStatCard.tsx
  packages/client/src/components/Chart/LineChart.tsx
  packages/client/src/containers/LineChartContainer.tsx
  packages/client/src/containers/TabContainer.tsx
  packages/client/src/lists/JobStatList.tsx
  packages/client/src/lists/WaitingList.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/server/api/score/score.controller.ts
  packages/server/api/score/score.service.ts
  packages/server/api/user/index.ts
  packages/server/api/user/user.service.ts
  packages/server/models/Score.ts
  yarn.lock
Labels: ✨ Feature, 🕊 API, 🧩 Component, 👶🏻 Frontend, 💻 Backend

#217 [TASK] 스켈레톤 UI 구현
  packages/client/src/components/Skeleton/SkeletonDefaultButton.tsx
  packages/client/src/components/Skeleton/SkeletonKeyframeAnimation.ts
  packages/client/src/components/Skeleton/SkeletonRoomCard.tsx
  packages/client/src/components/Skeleton/SkeletonRoomContainer.tsx
  packages/client/src/lists/RoomList.tsx
  packages/client/src/pages/Callback/index.tsx
  packages/client/src/templates/Header/index.tsx
Labels: ✨ Feature, 👶🏻 Frontend

#219 [PERFORMANCE] 리액트 성능 최적화
  packages/client/src/components/Toast/index.tsx
  packages/client/src/containers/GamePageModalContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/containers/ProfileCardContainer.tsx
  packages/client/src/containers/RightSideContainer.tsx
  packages/client/src/containers/WaitingListContainer.tsx
  packages/client/src/containers/WaitingTopBarContainer.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useGame.ts
  packages/client/src/hooks/useJobMemo.ts
  packages/client/src/hooks/useModal.ts
  packages/client/src/hooks/useToast.ts
  packages/client/src/lists/AbilityButtonList.tsx
  packages/client/src/lists/MemoList.tsx
  packages/client/src/lists/WaitingList.tsx
  packages/client/src/pages/Game/index.tsx
  packages/client/src/pages/Waiting/index.tsx
  packages/client/src/types/index.ts
  packages/socket/package.json
  yarn.lock
Labels: ⚡️ Performance

#223 [PERFORMANCE] 리액트 최적화, 조건부 렌더링 HOC 패턴 적용
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/containers/GamePageModalContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hoc/index.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useLog.ts
  packages/client/src/lists/AbilityButtonList.tsx
  packages/client/src/templates/Header/index.tsx
  packages/socket/sockets/game.ts
  packages/socket/stores/RoomStore.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend, ⚡️ Performance

#224 [12.04] 작업 분량
  packages/client/src/components/Button/AbilityButton.tsx
  packages/client/src/containers/GamePageModalContainer.tsx
  packages/client/src/containers/LeftSideContainer.tsx
  packages/client/src/hoc/index.tsx
  packages/client/src/hooks/useAbility.ts
  packages/client/src/hooks/useLog.ts
  packages/client/src/lists/AbilityButtonList.tsx
  packages/client/src/templates/Header/index.tsx
  packages/socket/sockets/game.ts
  packages/socket/stores/RoomStore.ts
Labels: ⚙️ Refactor, 👶🏻 Frontend, ⚡️ Performance

#225 [FIX] 배포 구성 변경
  .github/workflows/main.yml
  README.md
Labels: ✍🏻 Docs, 🏝 Environment

#226 [12.17] 작업 분량
  .github/workflows/main.yml
  README.md
Labels: ✍🏻 Docs, 🏝 Environment
